

# A list of all sites the username search checks

SITES = {

    "Reddit": {"url": "https://www.reddit.com/user/{}", "category": "social"},
    "Twitch": {"url": "https://www.twitch.tv/{}", "category": "social"},
    "X (Twitter)": {"url": "https://x.com/{}", "category": "social"},
    "Instagram": {"url": "https://www.instagram.com/{}", "category": "social"},
    "Facebook": {"url": "https://www.facebook.com/{}", "category": "social"},  #FLAGED FOR GETTING 200 ON ANOTHER SITE
    "TikTok": {"url": "https://www.tiktok.com/@{}", "category": "social"},
    "Snapchat": {"url": "https://www.snapchat.com/@{}", "category": "social"},
    "Pinterest": {"url": "https://www.pinterest.com/{}", "category": "social"},
    "Discord": {"url": "https://discord.com/users/{}", "category": "social"},
    "Threads": {"url": "https://www.threads.net/@{}", "category": "social"},
    "Mastodon": {"url": "https://mastodon.social/@{}", "category": "social"},
    "Bluesky": {"url": "https://bsky.app/profile/{}", "category": "social"},
    "TruthSocial": {"url": "https://truthsocial.com/@{}", "category": "social"},
    "VK": {"url": "https://vk.com/{}", "category": "social"},
    "OK.ru": {"url": "https://ok.ru/{}", "category": "social"},
#    "Medium": {"url": "https://medium.com/@{}", "category": "social"},
    "Behance": {"url": "https://www.behance.net/{}", "category": "social"}, #FLAGED FOR GETTING 200 ON ANOTHER SITE
    "Flickr": {"url": "https://www.flickr.com/people/{}", "category": "social"},
    "Tumblr": {"url": "https://www.tumbler.com/{}", "category": "social"},

    "Steam": {"url": "https://steamcommunity.com/id/{}", "category": "gaming"},
    "Xbox": {"url": "https://xboxgamertag.com/search/{}", "category": "gaming"},
    "PlayStation": {"url": "https://psnprofiles.com/{}", "category": "gaming"},
    "Roblox": {"url": "https://www.roblox.com/users/profile?username={}", "category": "gaming"},
    "Epic Games": {"url": "https://www.epicgames.com/account/personal?username={}", "category": "gaming"},
    "Riot Games": {"url": "https://www.op.gg/summoners/na/{}", "category": "gaming"},
    "Battle.net": {"url": "https://battle.net/account/management/{}", "category": "gaming"},
    "Minecraft": {"url": "https://namemc.com/profile/{}", "category": "gaming"},
    "Fortnite Tracker": {"url": "https://fortnitetracker.com/profile/all/{}", "category": "gaming"}, #403 Error
    "Itch.io": {"url": "https://{}.itch.io", "category": "gaming"},
    "Faceit": {"url": "https://www.faceit.com/en/players/{}", "category": "gaming"},
    "Tracker.gg": {"url": "https://tracker.gg/profile/{}", "category": "gaming"},
    "Speedrun.com": {"url": "https://www.speedrun.com/user/{}", "category": "gaming"},
    "Chess.com": {"url": "https://www.chess.com/member/{}", "category": "gaming"},
    "Lichess": {"url": "https://lichess.org/@/{}", "category": "gaming"},
    "GameJolt": {"url": "https://gamejolt.com/@{}", "category": "gaming"},
    "GOG": {"url": "https://www.gog.com/u/{}", "category": "gaming"},
    "EA": {"url": "https://myaccount.ea.com/cp-ui/aboutme/index?personaId={}", "category": "gaming"},
    "Ubisoft": {"url": "https://ubisoftconnect.com/en-US/profile/{}", "category": "gaming"},

    "GitHub": {"url": "https://github.com/{}", "category": "programming"},
    "GitLab": {"url": "https://gitlab.com/{}", "category": "programming"},
#    "Bitbucket": {"url": "https://bitbucket.org/{}", "category": "programming"}, #Needs sperate way to find account
#    "StackOverflow": {"url": "https://stackoverflow.com/users/{}", "category": "programming"}, #Creates Random Numbers In User Profile
    "Dev.to": {"url": "https://dev.to/{}", "category": "programming"},
    "HackerRank": {"url": "https://www.hackerrank.com/{}", "category": "programming"},
    "LeetCode": {"url": "https://leetcode.com/{}", "category": "programming"},
    "Kaggle": {"url": "https://www.kaggle.com/{}", "category": "programming"},
    "Replit": {"url": "https://replit.com/@{}", "category": "programming"},
    "Docker Hub": {"url": "https://hub.docker.com/u/{}", "category": "programming"},
    "Codeforces": {"url": "https://codeforces.com/profile/{}", "category": "programming"},
    "CodeChef": {"url": "https://www.codechef.com/users/{}", "category": "programming"},
    "AtCoder": {"url": "https://atcoder.jp/users/{}", "category": "programming"},
    "TopCoder": {"url": "https://www.topcoder.com/members/{}", "category": "programming"},
    "SourceForge": {"url": "https://sourceforge.net/u/{}/profile", "category": "programming"}, #FLAGED FOR GETTING 200 ON ANOTHER SITE
    "PyPI": {"url": "https://pypi.org/user/{}", "category": "programming"},
    "npm": {"url": "https://www.npmjs.com/~{}", "category": "programming"},
    "Gitpod": {"url": "https://gitpod.io/@{}", "category": "programming"},
    "Glitch": {"url": "https://glitch.com/@{}", "category": "programming"},

    "Quora": {"url": "https://www.quora.com/profile/{}", "category": "forums"},
    "HackerNews": {"url": "https://news.ycombinator.com/user?id={}", "category": "forums"},
    "XDA Developers": {"url": "https://forum.xda-developers.com/m/{}", "category": "forums"},
    "Linus Tech Tips": {"url": "https://linustechtips.com/profile/{}", "category": "forums"},
    "ResetEra": {"url": "https://www.resetera.com/members/{}", "category": "forums"},
    "GameFAQs": {"url": "https://gamefaqs.gamespot.com/community/{}", "category": "forums"},
    "NeoGAF": {"url": "https://www.neogaf.com/members/{}", "category": "forums"},
    "StackExchange": {"url": "https://stackexchange.com/users/{}", "category": "forums"},
    "Discourse": {"url": "https://discourse.org/u/{}", "category": "forums"},
    "Fandom": {"url": "https://community.fandom.com/wiki/User:{}", "category": "forums"},
    "Tapatalk": {"url": "https://www.tapatalk.com/groups/{}/", "category": "forums"},
    "Minecraft Forum": {"url": "https://www.minecraftforum.net/members/{}", "category": "forums"},
    "Guru3D": {"url": "https://forums.guru3d.com/members/{}", "category": "forums"},
    "Tom's Hardware": {"url": "https://forums.tomshardware.com/members/{}", "category": "forums"},

    "YouTube": {"url": "https://www.youtube.com/@{}", "category": "entertainment"},
    "Vimeo": {"url": "https://vimeo.com/{}", "category": "entertainment"},
    "SoundCloud": {"url": "https://soundcloud.com/{}", "category": "entertainment"},
    "Bandcamp": {"url": "https://{}.bandcamp.com", "category": "entertainment"},
    "Mixcloud": {"url": "https://www.mixcloud.com/{}", "category": "entertainment"},
    "Last.fm": {"url": "https://www.last.fm/user/{}", "category": "entertainment"},
    "DeviantArt": {"url": "https://www.deviantart.com/{}", "category": "entertainment"},
    "Spotify": {"url": "https://open.spotify.com/user/{}", "category": "entertainment"},
    "IMDb": {"url": "https://www.imdb.com/user/ur{}/", "category": "entertainment"},
    "Letterboxd": {"url": "https://letterboxd.com/{}", "category": "entertainment"},
    "AniList": {"url": "https://anilist.co/user/{}", "category": "entertainment"},
    "MyAnimeList": {"url": "https://myanimelist.net/profile/{}", "category": "entertainment"},
    "Trakt": {"url": "https://trakt.tv/users/{}", "category": "entertainment"},
    "Discogs": {"url": "https://www.discogs.com/user/{}", "category": "entertainment"},
    "RateYourMusic": {"url": "https://rateyourmusic.com/~{}", "category": "entertainment"},

    "Etsy": {"url": "https://www.etsy.com/people/{}", "category": "shopping"},
    "eBay": {"url": "https://www.ebay.com/usr/{}", "category": "shopping"},
    "Depop": {"url": "https://www.depop.com/{}", "category": "shopping"},
    "Poshmark": {"url": "https://poshmark.com/closet/{}", "category": "shopping"},
    "Mercari": {"url": "https://www.mercari.com/u/{}", "category": "shopping"},
    "Grailed": {"url": "https://www.grailed.com/{}", "category": "shopping"},
    "StockX": {"url": "https://stockx.com/portfolio/{}", "category": "shopping"},
    "Amazon": {"url": "https://www.amazon.com/gp/profile/amzn1.account.{}", "category": "shopping"},
    "AliExpress": {"url": "https://www.aliexpress.com/store/{}", "category": "shopping"},
    "Wish": {"url": "https://www.wish.com/profile/{}", "category": "shopping"},
    "Etsy Shop": {"url": "https://www.etsy.com/shop/{}", "category": "shopping"},
    "Newegg": {"url": "https://www.newegg.com/members/{}", "category": "shopping"},
    "Walmart": {"url": "https://www.walmart.com/account/{}", "category": "shopping"},
    "Target": {"url": "https://www.target.com/account/{}", "category": "shopping"},
    "Best Buy": {"url": "https://www.bestbuy.com/profile/{}", "category": "shopping"},
    "OfferUp": {"url": "https://offerup.com/p/{}", "category": "shopping"},
    "Carousell": {"url": "https://www.carousell.com/u/{}", "category": "shopping"},
    "Vinted": {"url": "https://www.vinted.com/member/{}", "category": "shopping"},
    "Shopee": {"url": "https://shopee.com/{}", "category": "shopping"},

    "Coursera": {"url": "https://www.coursera.org/user/{}", "category": "education"},
    "Udemy": {"url": "https://www.udemy.com/user/{}", "category": "education"},
    "Khan Academy": {"url": "https://www.khanacademy.org/profile/{}", "category": "education"},
    "edX": {"url": "https://www.edx.org/user/{}", "category": "education"},
    "Codecademy": {"url": "https://www.codecademy.com/profiles/{}", "category": "education"},
    "Brilliant": {"url": "https://brilliant.org/profile/{}", "category": "education"},
    "Duolingo": {"url": "https://www.duolingo.com/profile/{}", "category": "education"},
    "Skillshare": {"url": "https://www.skillshare.com/user/{}", "category": "education"},
    "Chegg": {"url": "https://www.chegg.com/profile/{}", "category": "education"},
    "Brainscape": {"url": "https://www.brainscape.com/p/{}", "category": "education"},
    "Udacity": {"url": "https://www.udacity.com/user/{}", "category": "education"},
    "FutureLearn": {"url": "https://www.futurelearn.com/profiles/{}", "category": "education"},
    "SoloLearn": {"url": "https://www.sololearn.com/profile/{}", "category": "education"},
    "OpenLearn": {"url": "https://www.open.edu/openlearn/profiles/{}", "category": "education"},
    "Pluralsight": {"url": "https://app.pluralsight.com/profile/{}", "category": "education"},
    "LinkedIn Learning": {"url": "https://www.linkedin.com/learning/instructors/{}", "category": "education"},
    "MIT OCW": {"url": "https://ocw.mit.edu/search/?q={}", "category": "education"},
    "HarvardX": {"url": "https://courses.edx.org/profiles/{}", "category": "education"},
    "StudyStack": {"url": "https://www.studystack.com/profile/{}", "category": "education"},


#   "Template" {"url": " ", "category": "adult"}
#    "PornHub Model": {"url": "https://www.pornhub.com/model/{}", "category": "adult"},
 #   "PornHub PornStar": {"url": "https://www.pornhub.com/pornstar/{} ", "category": "adult"},
  #  "PornHub User": {"url": "https://www.pornhub.com/users/{} ", "category": "adult"},
#    "Xvideos Model": {"url": "https://www.xvideos.com/models/{} ", "category": "adult"},
#    "Xvideos Channel": {"url": "https://www.xvideos.com/{} ", "category": "adult"},
#    "Xvideos User": {"url": "https://www.xvideos.com/profiles/{} ", "category": "adult"},
#    "xHampster Creator": {"url": "https://xhamster.com/creators/{} ", "category": "adult"},
#    "xHampster Channel": {"url": "https://xhamster.com/channels/{} ", "category": "adult"},
#    "xHampster User": {"url": "https://xhamster.com/users/profiles/{} ", "category": "adult"}

}
